### ISSUE TITLE
The issue is ME !

### ISSUE THREAD

**Issue by Sasch600xt** [greiman/SdFat#109]
Hello,

i am so sorry to waste your time with my beginner question, but i need a little help....

i use ATOM Platformio and an Arduino Mega 2560.
The SD card module is from AZdelivery.

i am looking for the simplest solution to do the follwing by writing values to variables and not print over serial:

`unsigned long cardsize_in_MB = // no idea what to put in here;
unsigned long free_space_in_MB = // no idea what to put in here;
unsigned long used_space_in_MB = // no idea what to put in here;
int how_many_files_on_card = // no idea what to put in here;`

I have to use SoftwareSPI because of trouble with my lora shield.
I used different SS ports, but no success.

Since i use SoftwareSPI i could get some examples working.

Here is my code so far (mod from an example)
But my question is: How can i get the values and set it to variables ?

I am so sorry for my skills, if somehow possible, please answere in a very simple way, so i can understand. For my code i only need this 4 variables to be set.

`#include <Arduino.h>
#include <SPI.h>
#include "SdFat.h"
#if ENABLE_SOFTWARE_SPI_CLASS  // Must be set in SdFat/SdFatConfig.h
#else  // ENABLE_SOFTWARE_SPI_CLASS
#error ENABLE_SOFTWARE_SPI_CLASS must be set non-zero in SdFat/SdFatConfig.h
#endif  //ENABLE_SOFTWARE_SPI_CLASS
//
// Pin numbers in templates must be constants.
const uint8_t SOFT_MISO_PIN = 30;
const uint8_t SOFT_MOSI_PIN = 31;
const uint8_t SOFT_SCK_PIN  = 32;
//
// Chip select may be constant or RAM variable.
const uint8_t SD_CHIP_SELECT_PIN = 33;

// SdFat software SPI template
SdFatSoftSpi<SOFT_MISO_PIN, SOFT_MOSI_PIN, SOFT_SCK_PIN> sd;

SdFile file;

unsigned long cardsize_in_MB = 0;
unsigned long free_space_in_MB = 0;
unsigned long used_space_in_MB = 0;
int how_many_files_on_card = 0;

void setup() {
  Serial.begin(9600);

  if (!sd.begin(SD_CHIP_SELECT_PIN, SD_SCK_MHZ(50))) {
    sd.initErrorHalt();
  }

  cardsize_in_MB = // no idea what to put here
  free_space_in_MB = // no idea what to put here or (cardsize_in_MB - used_space_in_MB) ?
  used_space_in_MB = // no idea what to put here
  how_many_files_on_card = // no idea what to put here

}
//------------------------------------------------------------------------------
void loop() {}`

Thank you sooooo much for your help !!!
have a great day
Sascha

**Comment by greiman** [comment]
Use the Arduino forum.
