### ISSUE TITLE
SoftwareSPI Write keeps overwriting 

### ISSUE THREAD

**Issue by KleinYuan** [greiman/SdFat#11]
Hi,
I tried to use Software SPI to log data from other Hardware SPI devices.
One thing keeps annoying me is that the write/print function will keep overwriting. Therefore, only thing I've got was the last data.
Do you know how to solve it?
I tried to use another file as temp but not working.

Looking forwards to your reply.

**Comment by greiman** [comment]
I have no Idea what hardware or program you are using.  Post example code that demonstrates the problem on the Arduino forum with full details of your hardware setup.

I don't have your hardware so I can only deal with a simple example program that demonstrates a problem, not a complex example that uses hardware I don't have.  

I test loggers with software SPI so I can't guess what you are doing.
