### ISSUE TITLE
Endless loop in FatVolume::allocContiguous

### ISSUE THREAD

**Issue by mjeanrichard** [greiman/SdFat#119]
Hi,

I (sometimes?) get an endless loop in when trying to ``createContiguous()``. 
The loop is in ``FatVolume::allocContiguous()``. The variable ``startCluster`` has a value of 1. Therefore the abort condition on line 157 (``if (startCluster == endCluster)``) is never true since ``endCluster`` is initialized to 2.

Am I missing something here? I assume that there is not enough space on the Card but this should not reult in an endless loop.

Thanks for your help!

**Comment by greiman** [comment]
You are correct, there is a bug in how m_allocSearchStart  is used that can cause an infinite loop.

I am working on a fix.

**Comment by mjeanrichard** [comment]
Cool, thanks!

**Comment by greiman** [comment]
Try the latest version.  

I modified the allocation algorithms since I found additional problems.

**Comment by mjeanrichard** [comment]
Thanks a lot fot the fast fix!
