### ISSUE TITLE
LED output does not work after sd.begin()

### ISSUE THREAD

**Issue by mahfiaz** [greiman/SdFat#13]
After doing sd.begin(10) blinking LED on pin 13 does not work anymore on Arduino Uno clone.

Stripped down example (blinks LED just once inside setup):
http://pastebin.com/ttP4FmsP

Am I doing something stupid?

**Comment by greiman** [comment]
Pin 13 is SPI SCK so you can’t use it to blink with an SD or any other SPI device.

**Comment by mahfiaz** [comment]
Thanks a lot for your prompt answer.
