### ISSUE TITLE
Particle Photon Support?

### ISSUE THREAD

**Issue by Jerware** [greiman/SdFat#15]
A year ago I floated the idea of porting SdFat to the Spark Core on their official forum. Unfortunately nothing came of it. They recently released a lower cost (and more powerful) version of that board called the Photon.

https://store.particle.io/

I would be happy to sponsor the purchase of one of these boards if it meant support for SdFat.

**Comment by greiman** [comment]
You should be able to use SdFat on Proton by modifying the Maple version.

See this file

https://github.com/greiman/SdFat/blob/master/SdFat/SdSpiSTM32F1.cpp
