### ISSUE TITLE
signed to unsigned conversion in return value

### ISSUE THREAD

**Issue by quarantadue** [greiman/SdFat#158]
comment say "return 1 for success and 0 for failure"
but FatFile::write(b) returns -1 for failure
because size_t is unsigned -1 is converted to some large value.
This could led to troubles when testing for errors

https://github.com/greiman/SdFat/blob/3b79f38cb554809a45a0ccd6d9d6752b6ad948c2/src/FatLib/ArduinoFiles.h#L226

**Comment by greiman** [comment]
I will modify the behavior [SdFat V2](https://github.com/greiman/SdFat-beta), now in beta.  I  have frozen V1 and don't want to change the behavior of V1. 

All write calls with return type size_t should return number of bytes written.  An error occurred if the return is not equal to the requested write size.
