### ISSUE TITLE
String error in SD.rename()

### ISSUE THREAD

**Issue by q24h** [greiman/SdFat#161]
Greetings,

I was doing a sequential renaming scheme in my code to split files into smaller bits, the filename is generated as a string. Using your rename function I encounter the following error 

> sdfat no matching function for call to 'SdFile::rename(String&)'

I was able to fix the problem using the code you had suggested in another issue (#134)

`    if ( file.rename(new_filename.c_str())) { `

I was wondering strings can be added for rename as well. Thanks!

**Comment by greiman** [comment]
SdFat V1 is frozen.  I plan to add rename with String type in [SdFat V2](https://github.com/greiman/SdFat-beta) now in beta.
