### ISSUE TITLE
'myFile' does not name a type

### ISSUE THREAD

**Issue by mytja** [greiman/SdFat#170]
error: 'myFile' does not name a type
myFile.open("map1.h", O_READ);

**Comment by greiman** [comment]
Don't have a clue from your limited info.  Have you declared myFile with something like this?

`  File myFile;`

**Comment by mytja** [comment]
Yes, I did

V V sob., 21. dec. 2019 ob 15:09 je oseba Bill Greiman <
notifications@github.com> napisala:

**Comment by greiman** [comment]
My crystal ball can't help. since you provided no code, no hardware info, and no IDE info.

Try this it should compile:

```
#include "SdFat.h"
File myFile;
void setup() {
  myFile.open("map1.h", O_READ);
}
void loop() {}
```
Output for an Uno.
```
Sketch uses 6264 bytes (19%) of program storage space. Maximum is 32256 bytes.
Global variables use 79 bytes (3%) of dynamic memory, leaving 1969 bytes 
for local variables. Maximum is 2048 bytes.
```
I am closing this since you provided no Info and I get about 20 requests for help every day with enough infor so I can help.
