### ISSUE TITLE
Missing SdVolume on SparkPlug MP3 2011 Code

### ISSUE THREAD

**Issue by promechitlungsei** [greiman/SdFat#18]
Hi I've searched on forums in Arduino and other web links online, but I'm am trying to test out the SparkPlug 2011 Code on my Arduino Nano, I've set the pins and included the correct libraries, but I'm missing SdVolume. I've looked at the text files of the changes and realized that it is deprecated, but then is there another function or even a library that I need to include for a function similar to SdVolume?

SdFat SD;
//Create the variables to be used by SdFat Library
//Sd2Card card;
// SdVolume volume;
SdFile root;
SdFile track;

UPDATE: Nevermind I saw that it is supposed to be included with the sdfat object, but for the SParkPlug Project would I replace every function that has SdVolume's object name and Sd2Card's object name with the name of my SdFat object? If you'd like I'm posting the example code for Arduino below.

Here's the link to the example code
http://cdn.sparkfun.com/datasheets/Dev/Arduino/Shields/MP3_Player_Example_Control.pde

I appreciate any help
Thanks Bill!

**Comment by greiman** [comment]
I rewrote SdFat in 2011 and released a version in July 2011 with SdVolume  internal to The SdFat class.

I don't intend to support use of the SdVolume class or it's replacement, FatVolume in user programs.

There should be no need for these internal classes in  user programs.

**Comment by promechitlungsei** [comment]
Is there any way to download the 2011 version of the SdFat library?

**Comment by greiman** [comment]
The 2011 versions no longer compile with current versions of the IDE.

The core of SD.h is a 2010 or 2011 version of SdFat.
