### ISSUE TITLE
508 bytes of data in 512 byte block size - Purpose of last 4 bytes?

### ISSUE THREAD

**Issue by censix** [greiman/SdFat#182]
Hi Bill

I have been using SdFat for several months now. I acquire ADC data at about 40k samples per second and write directly to an attached SD card. Works great!
... just one thing.
I acquire 254 samples(byte) in one data record. So two records fit into the  508 = 2*254
bytes for one block of 512, to be written to the SD card, using your library.

https://github.com/greiman/SdFat/blob/master/examples/AnalogBinLogger/AnalogBinLogger.h
// Data block for 8-bit ADC mode.
const size_t DATA_DIM8 = 508;

After looking closely at the binary log file on the card, I see that the last 4 bytes (509-512) of each block, apparently written by the SDFat library, never change. Their values are: 05 AF 00 0D.
Since all blocks end with these same four bytes, no matter what the data content of the block is, I am wondering why SDFat needs them.  They obviously don't contain a checksum of the data bytes, so why have them? I am asking since I would really like to use these four bytes for writing data values as well!

Q: Is there any specific reason why I should NOT use the last 4 bytes of each block for data? Will SDcard writing/reading fail if if do write data to them?

Thanks!

EDIT:
Correction. From "AnalogBinLogger.h" I see that the FIRST 4 bytes fo each 512-byte block are used for 'count' and 'overrun', and the rest is data:

// Data block for 8-bit ADC mode.
const size_t DATA_DIM8 = 508;
struct block8_t {
  unsigned short count;    // count of data values
  unsigned short overrun;  // count of overruns since last block
  unsigned char  data[DATA_DIM8];
};

But in my data, the first 4 bytes of nearly every block are
08 00 00 00
But 08 00 cannot be a data value count, since there are 508 (= 0x01FC )data values, 

So I should probably not repurpose the first 4 bytes, by writing data there, since that would mean changing the way SdFat works (don't want to do that). But I should look at what is happening with the last 4 bytes of each block, but that has to do with the way I am doing the ADC measurements and is therefore not an issue with SdFat. 

A comment would still be appreciated to see if my thinking is correct here. Thanks.

**Comment by greiman** [comment]
Entire 512 byte SD blocks must be written so the size the of struct block8_t or block16_t is 512 bytes.  

Depending on the pin count, part of the block may not be used. The first four bytes are used as an overrun count and a count of ADC values in the block.

**Comment by censix** [comment]
"Depending on the pin count, part of the block may not be used"
I see. Well I am only reading from one pin. So this should not be an issue.
I am now simply processing the .bin files with another step that cuts off the first 4 and the last 4 bytes. The result is acceptable for me.
Cheers
