### ISSUE TITLE
Issue with .createContiguous returning false

### ISSUE THREAD

**Issue by Bambofy** [greiman/SdFat#185]
See the original issue here: https://github.com/greiman/SdFs/issues/7

Do you know what would happen if the Arduino were to power off between writeStart and writeEnd?

**Comment by greiman** [comment]
The result would be undefined.  Each SD card has some RAM and data would be lost.

**Comment by Bambofy** [comment]
I've found that  if i run the program multiple times, the SD card fixes itself.

Start 1:
1. sd card ok
Start 2:
1. sd card cannot be used
Start 3:
1. sd card ok

Does this mean anything to you? i'm not sure why it would fix itself over restarts?

Finally, what would be the correct way to handle .createContiguous returning false? Should i erase and format the entire card?

**Comment by greiman** [comment]
Always reformat a card if you can't read or write files.

**Comment by Bambofy** [comment]
> Always reformat a card if you can't read or write files.

Thanks :)
