### ISSUE TITLE
SdFat only works on some SD slots

### ISSUE THREAD

**Issue by nostar** [greiman/SdFat#19]
I have 2 sainsmart 4.3 TFT displays with SDcard slots and 2 3.2 TFT displays.  One is a Sainsmart and one is the Coldtears original that all of these are cloned from.  SD library works on all 4, but SdFat only works on the 4.3 slots.  No read or write at all on the 3.2 slots.  The wiring and pinouts all seem to be the same.

**Comment by greiman** [comment]
Can't help since I don't have your hardware.  SD.h is just an old version of SdFat.  New versions of SdFat set the SPI options for each access and use 8MHz SPI.  The old SdFat in SD.h uses 4 MHz SPI and does not set SPI options after the begin() call.
