### ISSUE TITLE
SdFatSdioEx not defined for Teensy 4.1

### ISSUE THREAD

**Issue by XFer012** [greiman/SdFat#190]
Arduino sketches using "SdFatSdioEx" types do not build if Board = Teensy 4.1.
Using Arduino IDE 1.8.12, latest Teensyduino 1.52.
Same sketches build OK for Teensy 3.6.

**Comment by JaredReabow** [comment]
This is a problem but Xfer's description is slightly off, specifically the new SD beta has dropped support for "SdFatSdioEx" and as a result sdEx.

**Comment by greiman** [comment]
Teensy 4.x is not supported for SdFat.  
It may work with SdFat-beta but I don't have a Teensy 4.1 board.

**Comment by JaredReabow** [comment]
it does indeed work with T4.1

**Comment by JaredReabow** [comment]
are you getting a T4.1 bill?

**Comment by greiman** [comment]
See your SdFat-beta post.

**Comment by XFer012** [comment]
> 
> 
> Teensy 4.x is not supported for SdFat.

That's sad. :(
Ok then, case closed.
