### ISSUE TITLE
error: 'File' is already declared in this scope

### ISSUE THREAD

**Issue by Primus007** [greiman/SdFat#191]
i added in the example DirectoryFunctions the line: #include <ESP8266WiFi.h>

on compiling i get this error:

` In file included from C:\Users\pl\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.1\libraries\ESP8266WiFi\src/CertStoreBearSSL.h:26:0,
from C:\Users\pl\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.1\libraries\ESP8266WiFi\src/WiFiClientSecureBearSSL.h:30,
from C:\Users\pl\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.1\libraries\ESP8266WiFi\src/WiFiClientSecure.h:41,
from C:\Users\pl\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.1\libraries\ESP8266WiFi\src/WiFiServerSecure.h:20,
from C:\Users\pl\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.1\libraries\ESP8266WiFi\src/ESP8266WiFi.h:41,
from C:\Users\pl\AppData\Local\Temp\arduino_modified_sketch_295335\DirectoryFunctions.ino:7:
C:\Users\pl\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.1\cores\esp8266/FS.h:257:11: error: 'File' is already declared in this scope
using fs::File;
exit status 1
Fehler beim Kompilieren für das Board LOLIN(WEMOS) D1 R2 & mini.
`
how can i solve this?
Is there no sd library with timestamp they works with esp8266wifi??

**Comment by greiman** [comment]
You will need to contact the esp8266 people who made the wrappers for SdFat.

I will no longer support problems with SdFat in ESP8266.
