### ISSUE TITLE
SD card files are sometimes getting corrupted

### ISSUE THREAD

**Issue by xvinny** [greiman/SdFat#194]
Hello,

I wrote an application for ESP32 which integrates several peripherals like GPS, accelerometer, GSM and SD card.
One of the roles of the SD card is to store application logs wroten about 5 times per second.
There is only an instance of SdFat accessing the SD card, and I protected all the calls with a semaphore to avoid different threads calling SdFat at same time. For example:

```
bool StorageControllerClass::writeFile(String fileName, String content, size_t &bytesWritten)
{
    bool result = false;

    xSemaphoreTake(m_semaphoreStorageController, portMAX_DELAY);

    File file = SD.open(fileName, FILE_WRITE);
    if (!file)
    {
        ESP_LOGE(TAG_SDCARD, LOGE_0012, fileName.c_str());
        incrementWriteErrorCount();
    }
    else
    {
        resetWriteErrorCount();
        bytesWritten = file.write(content.c_str());
        if (bytesWritten <= 0)
            ESP_LOGE(TAG_SDCARD, SCC_LOGE_0003);

        file.close();
        result = true;
    }

    xSemaphoreGive(m_semaphoreStorageController);
    return result;
}
```

Sometimes, the log files are getting corrupted like this [https://1drv.ms/u/s!Avo94NMCzrU9godOZy5tGXFsdmhlQQ?e=fVpKvK](url)

Note that the files with more than 500MB are corrupted. I limit the files in 10MB, but when they get corrupted, they assume bigger sizes like 500MB, 4GB, etc.

I'm initializing SdFat with 20MHz speed:

`SD.begin(gpioNumber, SD_SCK_MHZ(20));`

As the device is installed in vehicles, it suffers with vibration and voltage changes. I think that an under voltage can be the cause, but I'm not sure because I currently don't monitor it.
Have you guys ever faced this kind of problem? Is it generally related to voltage issues?

Thank you. Regards,

Vinicius

**Comment by greiman** [comment]
I suggest you use the ESP SD library.  I do not plan to support SdFat on ESP since there are too many conflicts with ESP libraries.
