### ISSUE TITLE
Mount different partitions

### ISSUE THREAD

**Issue by LucasFeliciano21** [greiman/SdFat#203]
HI guys,

I'm trying to build an accessible drive using my stm32 with the USBcomposite library, but I don't want to show both partitions. 

So first I would need to be able to mount different partition. There is a way to do that and have multiple roots do access different partitions in the same card?

Many thanks

**Comment by greiman** [comment]
The SD standard specifies only one partition for a valid SD.  I only support cards formatted according to the standard.

**Comment by LucasFeliciano21** [comment]
Thanks @greiman, do you think there is some place that I can look to make that changes to the library?

Btw, I'll mark this as closed as you've answered me about it.
