### ISSUE TITLE
Difference between O_APPEND and O_AT_END

### ISSUE THREAD

**Issue by tellowkrinkle** [greiman/SdFat#225]
From the documentation, it seems like they should be the same (I would expect that opening a file at the end would make writes append to it)?

**Comment by greiman** [comment]
O_APPEND always seeks to the end of file for a write. 

O_AT_END opens the file at end of file but does not seek in write so you can rewrite other positions.

It's like the [fstream ](http://www.cplusplus.com/reference/fstream/fstream/open/)  modes app and ate.
