### ISSUE TITLE
please add "const" qualifier to ExFatFile::fileSize() getter

### ISSUE THREAD

**Issue by elhayra** [greiman/SdFat#236]
Hi,

Since this function is a simple getter, it should be const for safety and so it gets compiled with client const functions

**Comment by greiman** [comment]
I have quickly gone through .h files and added const to over 50 simple things like fileSize(). I will look for more cases where I need to change both the .h and .cpp files and then publish a new SdFat-beta to see what it breaks.  So in a week or two you will see a const fileSize().

I stopped paying attention to const after years of never hearing from users.  Good thing for me to start worrying about const again.

**Comment by greiman** [comment]
Try 2.0.4 for  improved "const correctness".

**Comment by elhayra** [comment]
thank you for the quick response.
closing.
