### ISSUE TITLE
Library documentation ( html pages )

### ISSUE THREAD

**Issue by Willena** [greiman/SdFat#24]
Hi ! thanks for your job,
I just want to bring my idea to improve a little thing that is not very important.

This is not really an issue, but it could be interesting to have a new branch, using github fonctionnalities, such as gh-page that allow you to put web content available on greiman.github.io/SdFat/ for example.

Why it could be interesting ? The documentation is currently in an "html" folder and can be moved or duplicated to a gh-pages branch. By doing this the documentation can be pushed online and always be up to date. 

Having this pages online is a lot more practical than having them somewhere in the developper hard disk. 

Thank in advance. 
Ps : Sorry for my very bad english, this is not my native language, I am french....

**Comment by greiman** [comment]
I may get to online documentation some day.  I have many requests for moving things to gethub and updating existing software.
