### ISSUE TITLE
Dedicated SPI

### ISSUE THREAD

**Issue by DriekdeGadgetfreak** [greiman/SdFat#244]
In the newest version Dedicated SPI is enabled by default. And does not work when there are more SPI devices, Seems dangerous to me.

**Comment by greiman** [comment]
Dedicated SPI is used in examples if it is enabled in SdFatConfig.h.  The legacy calls like sd.begin(CsPin) all use shared SPI.

The only way to get dedicated SPI is to explicitly specify DEDICATED_SPI using a begin call with SdSpiConfig as the argument like this.

```
#define SD_CONFIG SdSpiConfig(SD_CS_PIN, DEDICATED_SPI, SPI_CLOCK)

  if (!sd.begin(SD_CONFIG)) {
    // handle error
} 
```

**Comment by DriekdeGadgetfreak** [comment]
Thanx, very clear now.
