### ISSUE TITLE
Compile errors in FatPartition and FsCache

### ISSUE THREAD

**Issue by slabbi** [greiman/SdFat#259]
compile errors fixed
It was necessary to clear the temporary files after update.

**Comment by slabbi** [comment]
Was fine in 2.0.2, errors appear in 2.0.3 and 2.0.4

**Comment by greiman** [comment]
The Arduino IDE is really fragile.  It tries too hard to optimize builds.  When I test new versions I often need to clear temporary files when I try various options.  I have wasted many hours so I understand.
