### ISSUE TITLE
Sdfat csv write string

### ISSUE THREAD

**Issue by zerethor** [greiman/SdFat#26]
Is it actually possible to input a variable string to write in the csv? can't find a way to replace 
  sdout << F(
    "line 1,1,2.3,4.5\n"
    "line 2,6,7.8,9.0\n"
    "line 3,9,8.7,6.5\n"
    "line 4,-4,-3.2,-1\n") << flush;

with an actual String test= "line 1,1,2.3,4.5\n";

**Comment by greiman** [comment]
This sections just produces a test file for the read example.  It is not intended as a general way to write a CSV file.

The purpose of this example is to show how to read a CSV file using iostream extractors.

Post a question on the Arduino forum if you don't know how to write a CSV file.
