### ISSUE TITLE
How to store fgetpos struct in SD file?

### ISSUE THREAD

**Issue by JJGR93** [greiman/SdFat#261]
Hello, i'm trying to get actual file position with fgetpos(), write the position in a file in SD card and rebuild the struct for using it later with fsetpos() but i'm struggling trying to do that. Anyone could help me?

Actual code:

fspos_t* lastPos = 0;
...
File.fgetpos(lastPos);
...
//Save lastPos in SD file..
...
//Read lastPos from SD file...
...
File.fsetpos(lastPos);

Thank you very much.

**Comment by greiman** [comment]
You should use curPosition() andseekSet().  

```
File file;
uint32_t pos;

pos = file.curPosition();

// save pos

// read pos

file.seekSet(pos);
```

**Comment by JJGR93** [comment]
Thank you so much, i really appreciate your answer and your time.
