### ISSUE TITLE
Add library to library manager of Arduino 1.5 or above

### ISSUE THREAD

**Issue by ortegafernando** [greiman/SdFat#27]
Hi, in order to have autoupdates, could you adapt this library to arduino 1.5 format and add it to the library manager?

[https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ](url)

Regards

**Comment by greiman** [comment]
This version of SdFat is dead.  See SdFat-beta.

I may add SdFat to the library manager in the future but I have lost interest in Arduino.  I have ported SdFat to other systems that I use.
