### ISSUE TITLE
Creating a hidden file

### ISSUE THREAD

**Issue by zevero** [greiman/SdFat#30]
I was looking for quite a while now in both the documentation and in the web for SdFat hidden files support.
The only thing I found is the isHidden() command.
But there seems not to be a command setHidden() or equivalent. 
Did I overlook it?

**Comment by greiman** [comment]
There is no function to set the hidden attribute.

**Comment by zevero** [comment]
oh ... thats a pitty ... thank you nevertheless for letting me know.
And thank you for this outstanding library!
