### ISSUE TITLE
Switch between shared and dedicated SPI?

### ISSUE THREAD

**Issue by TheNitek** [greiman/SdFat#303]
I am using a shared SPI setup, but in certain situations I won't be using the other SPI devices while writing large files onto the SD card (downloading them over WiFi).
Is it possible to switch between shared and dedicated mode to benefit from the performance improvements for those downloads?

**Comment by greiman** [comment]
There is no way to switch between dedicated and shared mode.  In dedicated mode the SPI bus is always reserved by SPI.beginTransaction() and the SD is almost always enabled with the CS pin low.  This causes the SD card to optimize use of internal buffers and program large flash pages only when required.

I need to write an sd.end() call to match sd.begin().  This would allow calling sd.begin() in dedicated mode, write a large file to the  SD card, call sd.end() and then call sd.begin() in shared mode.  Writing sd.end() is on my todo list.
