### ISSUE TITLE
Get LFN for SFN

### ISSUE THREAD

**Issue by TheNitek** [greiman/SdFat#304]
I am trying to optimize the memory usage of my ESP8266 arduino sketch by using 8.3 SFN folder names internally, but LFN when needed for user output. Unfortunately when opening a folder by using the SFN, getName also returns the SFN:

```
sdfat::SdFile _currentFolder;
_currentFolder.open("BLUBBE~1");
char foldername[100];
_currentFolder.getName(foldername, sizeof(foldername));
```
results in "BLUBBE~1" while

```
sdfat::SdFile _currentFolder;
_currentFolder.open("blubberblub");
char foldername[100];
_currentFolder.getName(foldername, sizeof(foldername));
```
results in "blubberblub" (and `getSFN` would return `BLUBBE~1`). Is there any chance to open the folder using the SFN `BLUBBE~1`, but get the LFN ("blubberblub") later on?

**Comment by greiman** [comment]
No, open scans LFN entries before the SFN directory entry and the name you gave does not match the LFN so open assumes your file has no LFN since you provided a SFN.

FAT with LFNs assumed you would use the LFN since there is no one-one mapping between LFN and SFN.
