### ISSUE TITLE
Example code availability for Arduino Due board

### ISSUE THREAD

**Issue by prugit1** [greiman/SdFat#312]
I am trying to use Arduino Due for fast data logging.
There will be 10 analogue sensors connected and would like to achieve a sampling frequency of 25KHz.
I would like to know if the SdFat library supports fast data logging similar to that of AVR boards.
Maybe an example code must be helpful.

**Comment by greiman** [comment]
The AVR example depends on reading the ADC in an interrupt routine.  This is possible with Due but I have not done an example.

I don't know of the status of Due fast ADC libraries using interrupts like the AVR example.  Due is capable of very fast ADC rates with DMA.  I suspect a logger at well over 100 ksps is possible.

You would need to write the logging app.
