### ISSUE TITLE
Support for card removal and insertion

### ISSUE THREAD

**Issue by PaulStoffregen** [greiman/SdFat#333]
On Teensy we're trying to support SD card removal and insertion.  Several minor issues have come up.

Ideally we should have connected the socket's card detect switch to a GPIO pin.  That still may happen for future hardware, but it's not feasible when the card is on a "shield" with only the SPI pins.  There doesn't seem to be any sort of API to ask whether the card is still present and responding properly.  So far we're using SdCard status() and readCID() to poll whether the card is in the socket.  Not sure if that's proper?

When we detect the card has been removed, I'm not sure what the correct course of action would be.  Especially if the user pulls the card while SdFat has files open, what should we do to forcibly close those FsFile instances?  When a new card is inserted, the last thing we need is any state left in RAM about the previous card.

When the user puts a new card into the socket, SdFs.begin(config) seems to be the only way to get up and running again.  As nearly as I can tell, initializing the SPI or SDIO hardware is intertwined with initializing the card plugged into that hardware.  Or is there a way to initialize a just-inserted card without initializing all the SPI / SDIO hardware?

If you have any APIs or tips about how we should deal with card removing and insertion, I could really use some guidance?  Or maybe consider media removal & insertion APIs for the future?

**Comment by greiman** [comment]
The only sure way is a card detect switch.  The SD standard has a pullup enable command but sockets may have pullups. 

I tried to find a solutions but nothing is reliable.  And you can never just pull a card reliably.  So the user needs to tell the app I want to remove the card, app tells user OK to remove card.

**Comment by greiman** [comment]
It is safe to remove the SD when all files are closed.  You don't need to call sd.end() and calling sd.end(), which only is in SdFs, won't prevent corrupt files.
 
I often test a number of cards with the bench example.  I designed it so it is safe to remove the card after it prints the test results.

When you type a character to start a test I always call sd.begin().  This works whether or not a card has been changed.

I suggest having a user command for changing the card.  Close all files and then tell the user it's OK to remove the card.  Without a card detect switch you need another way to know when the new card is inserted.
