### ISSUE TITLE
begin class latency

### ISSUE THREAD

**Issue by marcomauro** [greiman/SdFat#34]
I would like to use the sd.begin() class to test if the card is connected to the board. 
I check the connection using this piece of code:

```
/* check if the SD card is connected */
boolean SDconnected(void)
{
  boolean flagSD = false;
  /* Initializes the SD library and card. This begins use of the SPI bus and chip select pin */
  flagSD = sd.begin(CHIP_SELECT);
  return flagSD;
}
```

I have observed a latency of about 1 sec when I call SDconnected() function. 
Is there any chance to remove the latency ?

**Comment by greiman** [comment]
No, the latency must be there.  Some cards take that long to initialize.

You should use an SD socket with a Card Detect Switch.
