### ISSUE TITLE
Csv Go To Line

### ISSUE THREAD

**Issue by podaen** [greiman/SdFat#347]
I having problems to go to the next line without overwriting the previous line. Can someone help me out with this?

```
void WriteSongToPlaylist(int No, char* dirPath, char* filename, char* Dbfilename) {
	char* WriteString;
	char cNoStr[16];

	if (!openDbFile(dirPath, Dbfilename)) {
		error("opening file in folder failed");
	}
	else
	{
		itoa(No, cNoStr, 10);//convert number in to string
		if (No == 0) {//first line
			WriteString = CombineStrings(cNoStr, ";");
			WriteString = CombineStrings(WriteString, filename);
			WriteString = CombineStrings(WriteString, "\r\n");
			Serial.print("WriteString: ");
			Serial.println(WriteString);
		}
		else {//all other lines
			WriteString = "\r";
			for (int i = 1; i < No; i++) {//go to line
				Serial.println("x new line");
				WriteString = CombineStrings(WriteString, "\r");
			}
			WriteString = CombineStrings(WriteString, cNoStr);
			WriteString = CombineStrings(WriteString, ";");
			WriteString = CombineStrings(WriteString, filename);
			Serial.print("WriteString: ");
			Serial.println(WriteString);
		}
		DbFile.print(F(WriteString));
		DbFile.close();
	}
}
```

**Comment by podaen** [comment]
An other question... how is this working... opening next?

If I add a file to the directory, will it automaticly added the file AFTER all files that where allready in the directory?  Or is there someting like sorting the files?

**Comment by podaen** [comment]
One solution is by not closing the csv file until all lines are written.

**Comment by greiman** [comment]
You should read the documentation in libraries/SdFat/doc/.  Unzip html.zip and open SdFat.html in a browser.

You will find options for opening a file, like at end.  Here is documentation for oflag in open(path, oflag)

![oflag](https://user-images.githubusercontent.com/3964207/141683367-74a33dfd-011c-4b56-a7da-88b1377a5666.png)

Also look at more examples.

**Comment by podaen** [comment]
intresting... Thanks.

**Comment by podaen** [comment]
Can I open/creat multiple files at the same time?

**Comment by greiman** [comment]
> Can I open/creat multiple files at the same time?

Yes
