### ISSUE TITLE
This library does support flash memories?

### ISSUE THREAD

**Issue by fatmehosseini** [greiman/SdFat#348]
Hi, 
First of all thank you for this good and useful library. 
I am trying to use your library for at45db161 nor flash memory with QuickStart example . but it does not work and SD initialization fail. the wiring is correct and work with other libraries and codes and they are able to red and write on chip but not in FAT format. I've tried some solutions like decreasing frequency of SPI and increasing SD_INIT_TIMEOUT  value but they didn't worked neither. 
Now, my question is that does SDFAT library support flash memories or I am doing some thing wrong?

**Comment by greiman** [comment]
SdFat only supports SD cards with FAT16 or FAT32 filesystems.  There is no support for chips like at45db161.
