### ISSUE TITLE
Can I change the value size of FILE_BLOCK_COUNT?

### ISSUE THREAD

**Issue by schosdas** [greiman/SdFat#363]
I am modifying and using the Low Latency Logger example.
I want to save the sensor's value in the sd card for 1 hour at 500 Hz speed.
However, about 45 minutes later, it is displayed on the serial as 'File size: 256,000 blocks' and stops.

I think it's because the file block is full of the maximum size, is it okay to give a larger value of "FILE_BLOCK_COUNT"? 
(I think I need to save at least twice as much data as I do now)

Thank you.

**Comment by greiman** [comment]
You can increase FILE_BLOCK_COUNT in LowLatencyLogger.

You might want to look at [ExFatLogger](https://github.com/greiman/SdFat/blob/master/examples/ExFatLogger/ExFatLogger.ino), It will log to FAT16/FAT32 cards but is optimized for exFAT which has superior pre-allocate features.
