### ISSUE TITLE
Question: File (or its original type) or SdFile

### ISSUE THREAD

**Issue by gvisca44** [greiman/SdFat#366]
Hi there, 

I have been pouring over your code over the last week, and am curious.

Do you have a recommendation on when to use File vs. SdFile ?

eg. 
`SdFat sd ;`
`File file ;`
`    // etc. etc.`

versus
`SdFat sd ;`
`SdFile file ;` 
`   // etc. etc.`

Far too many inheritances meshed with templates to keep it all clear in my head !! :-)

One reason that I've found is that `File` doesnt expose dateTimeCallback (although there are ways around that).

Many thanks, 

Glenn.

**Comment by greiman** [comment]
If you have sufficient memory use:
```
  SdFs sd;
  FsFile file;  // Supports the  Arduino Stream class for FAT16/FAT32/exFAT.
```
The File class is defined in SdFatConfig.  By default this is FsFile except for 32KB AVR boards.

```
//------------------------------------------------------------------------------
/**
 * File types for SdFat, File, SdFile, SdBaseFile, fstream,
 * ifstream, and ofstream.
 *
 * Set SDFAT_FILE_TYPE to:
 *
 * 1 for FAT16/FAT32, 2 for exFAT, 3 for FAT16/FAT32 and exFAT.
 */
#ifndef SDFAT_FILE_TYPE
#if defined(__AVR__) && FLASHEND < 0X8000
// 32K AVR boards.
#define SDFAT_FILE_TYPE 1
#else  // defined(__AVR__) && FLASHEND < 0X8000
// All other boards.
#define SDFAT_FILE_TYPE 3
#endif  // defined(__AVR__) && FLASHEND < 0X8000
#endif  // SDFAT_FILE_TYPE
```
