### ISSUE TITLE
ExFatFile::open with O_RDONLY fails to open an existing file.

### ISSUE THREAD

**Issue by nopjne** [greiman/SdFat#381]
I modified the bench example to only open an existing file and execute only the read test. Truncate and Write are not being called anymore.

ExFatFile::m_validLength is always zero, so ExFatFile::read returns 0 bytes read. ExFatFile::openPrivate attempts to go into create mode which consequently fails because the O_CREAT flag is not specified.

Are there any rules about using O_RDONLY?

**Comment by greiman** [comment]
O_RDONLY can only open an existing file.

**Comment by greiman** [comment]
I am closing this since I can't waste time helping you modify examples.

**Comment by nopjne** [comment]
I see, no worries, just wanted to note:
The file is present, created from a previous run and viewable in a different reader.
file.exists("bench.dat") returns false though, so I'll look into that.
