### ISSUE TITLE
Webserver and SdFat

### ISSUE THREAD

**Issue by podaen** [greiman/SdFat#403]
I want to create a webserver with SdFat and I don't know how to do because all webserver lib are using FS and that doesn't work with SdFat as far as I understand. Please help.

**Comment by greiman** [comment]
If FS.h is supported by a systems, the legacy type File can't be used with SdFat.  File was defined by Arduino in the SD.h wrapper for SdFat in 2010.  I added a typedef for File  to provide compatibility with SD.h.

Just use FsFile in place of File and SdFs in place of SdFat.  These types support FAT16/FAT32 and exFAT.

Here is the section of SdFat.h that handles definition of the type File:

```
// Only define File if FS.h is not included.
// Line with test for __has_include must not have operators or parentheses.
#if defined __has_include
#if __has_include(<FS.h>)
#define HAS_INCLUDE_FS_H
#warning File not defined because __has_include(FS.h)
#endif  // __has_include(<FS.h>)
#endif  // defined __has_include
#ifndef HAS_INCLUDE_FS_H
#if SDFAT_FILE_TYPE == 1 || defined(DOXYGEN)
/** Select type for File. */
typedef File32 File;
#elif SDFAT_FILE_TYPE == 2
typedef ExFile File;
#elif SDFAT_FILE_TYPE == 3
typedef FsFile File;
#endif  // SDFAT_FILE_TYPE
#endif  // HAS_INCLUDE_FS_H
```
