### ISSUE TITLE
Repeated use of sd.begin on ESP32 will cause freeze

### ISSUE THREAD

**Issue by gary7530** [greiman/SdFat#418]
The first time I use sd.begin in loop() is fine, but the second time I use sd.begin will cause ESP32 to freeze

ESP32 stuck in activate();
https://github.com/greiman/SdFat/blob/628effa1c277e6dc1fef461b4b755ad300735248/src/SpiDriver/SdSpiArduinoDriver.h#L42

**Comment by greiman** [comment]
Try calling [sd.end()](https://github.com/greiman/SdFat/blob/628effa1c277e6dc1fef461b4b755ad300735248/src/SdFat.h#L118) before leaving the loop.

end() will call SPI::endTransaction()  to cancel any calls to activate()  which calls SPI::beginTransaction().
