### ISSUE TITLE
STM32l432kc Inizialization failed whe i do the SD.begin

### ISSUE THREAD

**Issue by lraton** [greiman/SdFat#429]
I have swiched from the classic sd library to this (because is more update and with the oled diplay(i2c) he doesn't like it and with the pn532 (i2c) module he doesn't let him read the cards anymore, but this is a problem for another time) and when i do the SD.begin it return false, whit the classic library it work, but with this no

**Comment by greiman** [comment]
Try the [QuickStart](https://github.com/greiman/SdFat/blob/master/examples/QuickStart/QuickStart.ino) example.

Post any error information.

**Comment by lraton** [comment]
With that example it works 'Card successfully initialized.'

**Comment by lraton** [comment]
Still block when i do display.display() (send buffer to oled, i found that probably the problem is the sram but i have 64 kb) and with the pn532 still won't let me scan the rfid/nfc card

**Comment by greiman** [comment]
Which STM32 board package are you using?  I have seen stack size problems in some board packages when using SPI array transfers since a 512 byte tmp buffer is needed.

**Comment by lraton** [comment]
I'm using the stm32 Duino https://github.com/stm32duino/Arduino_Core_STM32

**Comment by lraton** [comment]
i don't know, i can't find a solution for the oled and sd toghether, nobody know the solution :(
