### ISSUE TITLE
Case sensible file name

### ISSUE THREAD

**Issue by LaurentG91** [greiman/SdFat#44]
Hello,
Why file names (now long one) are not case sensible.
Are there any possibility: a boolean or function, to have a case sensible library.
Very useful when you upload file on the SD card from WiFi (ESP8266).
Thanks a lot

**Comment by greiman** [comment]
> Are there any possibility: a boolean or function, to have a case sensible library.

No, FAT16/FAT32 long file names are not case sensitive.  I can't change the standard.

**Comment by LaurentG91** [comment]
OK, thanks a lot and congratulation again for this very important improvement for SD reader...
