### ISSUE TITLE
AnalogBinLogger- Reading Two Analog Values and storing in SD

### ISSUE THREAD

**Issue by Gosakan** [greiman/SdFat#51]
Hi,

I have been working on storing analog values of two inputs and storing them on the SD Card using the code and instructions given in # **https://github.com/greiman/SdFat/tree/master/AnalogBinLoggerExtras** . However it doesnt provide enough information on how to store two different inputs at the same time using the Timer/Counter. Being a newbie to embedded C programming ,im unable to figure how to modify this code and use it for my purpose. Any help /info would be nice.

**Comment by greiman** [comment]
AnalogBinLogger can only store values from the AVR ADC.   This restriction is necessary to obtain max performance.

You could try to modify the LowLatencyLogger example.
