### ISSUE TITLE
analogRead A7 inside LowLatencyLogger with Feather M0

### ISSUE THREAD

**Issue by Hallulla** [greiman/SdFat#53]
Not sure if this is an issue or something I'm doing wrong:
I am using the Adalogger FeatherWing on top of a M0 BasicProto to log some sensor data into an SD card at 100hz. For this I have modified the LowLatencyLogger example and so far it works great. Now I need to implement some form of battery voltage reading so the program can stop recording and close the file before the battery runs out. For this I need to do an analogRead on pin A7(aka digital pin 9) which is connected to the battery via a voltage divider, I have added this code inside the logData() function: 
```
vBat = readBat();
if (vBat <= 3.35) {
  Serial.println("Battery low, closing file");
  closeFile = true;
}
```
where readBat() is:
```
float readBat() {
  float voltage = analogRead(VBATPIN);
  voltage *= 2;
  voltage *= 3.3;
  voltage /= 1024;
  return voltage;
}
```
Which prints the following: 
```
error: createContiguous failed
SD errorCode: 0X4,0X4
```
My guess was that there might be some pin conflicts but according to my research that is not the case here.  Do you know why this happens/how could I implement it correctly? 

PS: I understand I should probably filter the values returned by the readBat() function in order for this to work properly.

**Comment by greiman** [comment]
I never used an M0 Basic Proto and can't help you.
