### ISSUE TITLE
SdFat and RFduino SPI

### ISSUE THREAD

**Issue by andreydung** [greiman/SdFat#58]
I need to run SdFat with RFduino.[ RFduino API of SPI](https://github.com/RFduino/RFduino/blob/master/libraries/SPI/SPI.h) seems to be old and does not match SdFat, for example it does not have SPISettings class.

Is it realistic to upgrade SPI to match SdFat (If I were to do it)? Could you please provide some guidance on how to do that? For now, I'm thinking of adding SPISettings class.

**Comment by greiman** [comment]
You probably could add the SPISettings class.  beginTransaction() and endTransaction() are not easy if you want to match the Arduiono behavior of allowing SPI in interrupt service routines.

I can't help you.
