### ISSUE TITLE
Slow reading of free space

### ISSUE THREAD

**Issue by andreydung** [greiman/SdFat#59]
I'm checking free space of SD card (Sandisk, 64G, formatted by official SD formatter):

``` 
 uint32_t freeSpace = SD.vol()->freeClusterCount() * SD.vol()->blocksPerCluster();
```

This line takes 54s to finish. Is this normal? I'm using RFduino with SDfat (SPI of RFduino has been rewritten to work with SdFat).

For the modification of SPI class of RFduino, I simply added a class for SPISettings (note that it is not actually used, just a placeholder):

```
class SPISettings {
	// placeholder so that SdFat could be used
  public:
	SPISettings(uint32_t clock, uint8_t bitOrder, uint8_t dataMode) {
	};
	SPISettings() {
	};
};
```

Then added beginTransaction and endTransaction that actually called the default begin and end of RFduino:

```
	inline void beginTransaction(SPISettings settings) {
		begin();
	};
	inline void endTransaction(void) {
		end();
	};
```

And after this, SdFat works on RFduino, and I was able to write to SD card!

My concrete question  is that: is the slow speed due to incomplete porting of SPI.h, or due to parameters: Rfduino SPI default frequency is set to 4MHz (but is 4000 in the code)?

**Comment by stevstrong** [comment]
Running the standard SdInfo sketch will also take some time till "freeClusters: " display the result.

**Comment by greiman** [comment]
beginTransaction() should set only the SPI speed , bit order, and data mode.   begin() will set the default speed/mode but may be slower since the SPI controller will be initialized. 

freeClusterCount() must read the entire FAT to find the free cluster count.  This will take a long time for a 64G card.  

You can limit reading the FAT to the first call by setting this symbol at about line 80 of SdFatConfig.h.

```
//------------------------------------------------------------------------------
/** 
 * Set MAINTAIN_FREE_CLUSTER_COUNT nonzero to keep the count of free clusters
 * updated.  This will increase the speed of the freeClusterCount() call
 * after the first call.  Extra flash will be required.
 */
#define MAINTAIN_FREE_CLUSTER_COUNT 0
```

**Comment by stevstrong** [comment]
I tried to set `MAINTAIN_FREE_CLUSTER_COUNT to "1"` but it did not help, the SdInfo sketch still take the same amount of time to return freeClusterCount(). So I guess this is inevitable for the first time this function is called.

**Comment by andreydung** [comment]
Thanks all! I tried a smaller card (32Gb) and with the new method it's down to 3 sec.

I just need to monitor and check that data collection to SD card is working fine. Are there any other alternative statistics that could be performed much faster? I'm looking for the range of 10ms.

**Comment by greiman** [comment]
The first call to freeClusterCount() after SD.begin() will take a long time.

If MAINTAIN_FREE_CLUSTER_COUNT is nonzero, the time should be much less than a ms after the first call.

Here is the code:

```
int32_t FatVolume::freeClusterCount() {
#if MAINTAIN_FREE_CLUSTER_COUNT
  if (m_freeClusterCount >= 0) {
    return m_freeClusterCount;
  }
#endif  // MAINTAIN_FREE_CLUSTER_COUNT
```

**Comment by greiman** [comment]
closed
