### ISSUE TITLE
Sometimes library doesn't correctly identify my card as SDHC

### ISSUE THREAD

**Issue by schlaegerz** [greiman/SdFat#82]
I'm debugging some occasional failures and I see sometimes that it is not detecting that the card is SDHC. This then causes everything to start to fail.

Any idea why that would happen?

**Comment by greiman** [comment]
I have no idea what you are doing.

**Comment by schlaegerz** [comment]
Everyone once in a while it fails when i call:

SD->begin(SD_CHIP_SELECT, SPI_EIGHTH_SPEED)

After debugging into it I see that it doesn't think that my card is SDHC, so it has a read error after incorrectly reading a file.

**Comment by greiman** [comment]
begin() failures are due to hardware problems.

I don't have your hardware so I can't guess what is happening.
