### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by aster94** [greiman/SdFat#83]
hello,

i think there is an overcalling of error variables:
https://forum.arduino.cc/index.php?topic=509050.0

**Comment by greiman** [comment]
```
  if (!file.sync() || file.getWriteError()) {
    error("write error");
  }
```

The purpose of this code is to force data to the SD, update the directory entry and check for any errors.

file.sync() must be called to to accomplish this.  sync() may return true but a write error may have occurred earlier.

You could just test for write error like this but I tend to check each operation if it returns status.
```
  file.sync();
  if (file.getWriteError()) {
    error("write error");
  }
```

**Comment by aster94** [comment]
Ok, calling getWriteError or getError should be the same, isn t it?

**Comment by greiman** [comment]
Here are functions that access m_error.  Currently two bits are defined.

getWriteError() and clearWriteError() are members of the Print class as defined by Arduino.

getError() and clearError() are members of FatFile.

```
  static const uint8_t WRITE_ERROR = 0X1;
  static const uint8_t READ_ERROR  = 0X2;

 /** \return value of writeError */
  bool getWriteError() {
    return m_error & WRITE_ERROR;
  }
  /** Set writeError to zero */
  void clearWriteError() {
    m_error &= ~WRITE_ERROR;
  }
  /** Clear all error bits. */
  void clearError() {
    m_error = 0;
  }
  /** \return All error bits. */
  uint8_t getError() {
    return m_error;
  }
```
