### ISSUE TITLE
Question about SdFat

### ISSUE THREAD

**Issue by Strooom** [greiman/SdFat#84]
Bill, I'm trying to understand how your library works, but I'm stuck in how the memory management works..

When opening a file on the SD-card, the open function returns that File object. But when I look at the code I see it is creating it on the stack with local scope.. How can it be safe to use the returned (pointer to) the File object, if it went out of scope ? Here's the piece of code I found in **FatFileSystem.h** that seems to open the file..
 ```
File open(const char *path, uint8_t mode = FILE_READ) {
    File tmpFile;
    tmpFile.open(vwd(), path, mode);
    return tmpFile;
  }
```
From the doxygen documentation I can't figure it out.. Do you have additional documentation ?

**Comment by greiman** [comment]
This version of open returns an object, not a pointer.  The copy constructor for File is used to return the tmpFile object to the calling program.

Actually an optimization, [copy elision](http://www.geeksforgeeks.org/copy-elision-in-c/),  may occur that avoids the copy constructor.
