### ISSUE TITLE
add callback to freeClusterCount

### ISSUE THREAD

**Issue by mvladic** [greiman/SdFat#85]
Since reading of free space is inherently slow (see #59), is it possible to give `freeClusterCount()` a pointer to function which will be called after each `fatGet` or `cacheFetchFat` so we can continue doing our house keeping stuff while free space is calculated? Of course, this would be an optional argument so we stay backward compatible.

**Comment by greiman** [comment]
I will not add callbacks.

Edit SdFatConfig.h and set MAINTAIN_FREE_CLUSTER_COUNT non-zero. Then only the first call will take time.

```
//------------------------------------------------------------------------------
/**
 * Set MAINTAIN_FREE_CLUSTER_COUNT nonzero to keep the count of free clusters
 * updated.  This will increase the speed of the freeClusterCount() call
 * after the first call.  Extra flash will be required.
 */
#define MAINTAIN_FREE_CLUSTER_COUNT 0
```
