### ISSUE TITLE
Crash when removing file if the SD file is invalid.

### ISSUE THREAD

**Issue by schlaegerz** [greiman/SdFat#89]
I end up in a Watchdog restart in remove() when there is an invalid file if the next cluster points back to zero. This seems to happen if I lost power while writing occastionally.

I seem to be able to fix it by changing FreeChain:

```bool FatVolume::freeChain(uint32_t cluster) {
  uint32_t next;
  int8_t fg;
  do {
    fg = fatGet(cluster, &next);
    if (fg < 0) {
      DBG_FAIL_MACRO;
      goto fail;
    }
    // free cluster
    if (!fatPut(cluster, 0)) {
      DBG_FAIL_MACRO;
      goto fail;
    }
    // Add one to count of free clusters.
    updateFreeClusterCount(1);

    if (cluster < m_allocSearchStart) {
      m_allocSearchStart = cluster;
    }
    cluster = next;
  } while (fg && cluster);

  return true;

fail:
  return false;
}

**Comment by greiman** [comment]
This is not a safe fix.

**Comment by schlaegerz** [comment]
I don't get why it is not? All I'm doing is preventing a certain infinite loop. 
Other equal solution I found was to make sure fatPut fails if you try to write an invalid spot.

```
bool FatVolume::fatPut(uint32_t cluster, uint32_t value) {
  uint32_t lba;
  cache_t* pc;

  // error if reserved cluster of beyond FAT
  DBG_HALT_IF(cluster < 2 || cluster > m_lastCluster);
  if(cluster < 2 || cluster > m_lastCluster)
  {
    return false;
  }```

**Comment by greiman** [comment]
The problem with simple fixes to a corrupt file system is that clusters may be allocated to multiple files or other problems that can cause many files to be lost or corrupted.

The problem that causes the corrupt file needs to be fixed.

I will make the DBG_HALT error always fatal.
