### ISSUE TITLE
If you try to remove a file that is not formatted correctly you free the blocks but dont reomve the dir entry

### ISSUE THREAD

**Issue by schlaegerz** [greiman/SdFat#93]
Repro is:

Start writing a file on the SD card, lose power in the middle of the write.
Try to remove that file SD->remove("file.txy")

Result: 
Have a file that windows says "first allocation unit is not valid. The entry will be truncated." and you can't remove the file at all with the ESP8266

I can fix make a crappy fix:

```
bool FatFile::remove() {
  bool last;
  uint8_t chksum;
  uint8_t ord;
  FatFile dirFile;
  dir_t* dir;
  ldir_t* ldir;

  // Cant' remove not open for write.
  if (!isFile() || !(m_flags & O_WRITE)) {
    DBG_FAIL_MACRO;
    goto fail;
  }
  // Free any clusters.
  if (m_firstCluster && !m_vol->freeChain(m_firstCluster)) {

   // comment out these two lines
   // DBG_FAIL_MACRO;
   // goto fail;
  }
```

There is probably a better fix for this, but in my case I'd rather risk the chains floating around than have a file I cant get rid of.

**Comment by greiman** [comment]
I agree, it's a crappy fix. Who knows how corrupt your file system will become.

Better to repair the SD with Windows utility.
