### ISSUE TITLE
Time delay between selected bins

### ISSUE THREAD

**Issue by MNFuad** [greiman/SdFat#95]
I have tried to use this code for logging the 3-phase power data, 
I set the bins to be,
I1, I2, I3, V1, V2, V3 (3phase power) ==> 0, 1, 2, 3, 4, 5 (in the code)

When I try to plot the voltage (e.g. V1)  with the correspondence current (e.g. I1), the phase shift between the signals is not correct, so I assume there is some delay between the bin 3 and 4.

I thought it works exactly like the multiplexer, taking the first sample of all bins simultaneously.

Please correct me If I am wrong, any advice for solution would be appreciated.

note:
Is it possible to create multiple bin files with minimal delay. I want to log data for long time and don't want the file size to be huge. I tried to use "for loop" so that each file holds data for 30 minutes, it works but there is delay between files.

Thanks

**Comment by greiman** [comment]
I have no idea how you are using SdFat and don't have time help you with techniques for high speed data logging. 

Use the Arduino Forum for programming help.
